- variant: "1.26-trixie"
  tags:
    # renovate: datasource=docker depName=golang
    - "1.26.4-trixie"
    - "1.26-trixie"
    - "1-trixie"
    # renovate: datasource=docker depName=golang
    - "1.26.4"
    - "1.26"
    - "1"
  debian_variant: "trixie"
  build_args:
    # renovate: datasource=docker depName=golang
    GOLANG_TAG: "1.26.4-trixie@sha256:bbf22ddccb3205344f2755ea8fa4fe39f7a8b2b77b9f7b764ec2aad31406f6fc"

- variant: "1.26-bookworm"
  tags:
    # renovate: datasource=docker depName=golang
    - "1.26.4-bookworm"
    - "1.26-bookworm"
    - "1-bookworm"
  debian_variant: "bookworm"
  build_args:
    # renovate: datasource=docker depName=golang
    GOLANG_TAG: "1.26.4-bookworm@sha256:5f68ec6805843bd3981a951ffada82a26a0bd2631045c8f7dba483fa868f5ec5"

- variant: "1.25-trixie"
  tags:
    # renovate: datasource=docker depName=golang
    - "1.25.11-trixie"
    - "1.25-trixie"
    # renovate: datasource=docker depName=golang
    - "1.25.11"
    - "1.25"
  debian_variant: "trixie"
  build_args:
    # renovate: datasource=docker depName=golang
    GOLANG_TAG: "1.25.11-trixie@sha256:97df26d790e55489265c4c79ebffcb4242b6807d38d645e186516e518a6098b0"

- variant: "1.25-bookworm"
  tags:
    # renovate: datasource=docker depName=golang
    - "1.25.11-bookworm"
    - "1.25-bookworm"
  debian_variant: "bookworm"
  build_args:
    # renovate: datasource=docker depName=golang
    GOLANG_TAG: "1.25.11-bookworm@sha256:bbb255b0e131db500cf0520adc97441d2260cf629c7fa7e39e025ddf53995a24"
