- variant: "1.26-trixie"
  tags:
    # renovate: datasource=golang-version depName=golang versioning=semver
    - "1.26.4-trixie"
    - "1.26-trixie"
    - "1-trixie"
    # renovate: datasource=golang-version depName=golang versioning=semver
    - "1.26.4"
    - "1.26"
    - "1"
  debian_variant: "trixie"
  build_args:
    # renovate: datasource=golang-version depName=golang
    GOLANG_VERSION: "1.26.4"
    # renovate: datasource=go depName=golang.org/x/tools/gopls
    GOPLS_VERSION: "v0.22.0"

- variant: "1.26-bookworm"
  tags:
    # renovate: datasource=golang-version depName=golang versioning=semver
    - "1.26.4-bookworm"
    - "1.26-bookworm"
    - "1-bookworm"
  debian_variant: "bookworm"
  build_args:
    # renovate: datasource=golang-version depName=golang
    GOLANG_VERSION: "1.26.4"
    # renovate: datasource=go depName=golang.org/x/tools/gopls
    GOPLS_VERSION: "v0.22.0"

- variant: "1.25-trixie"
  tags:
    # renovate: datasource=golang-version depName=golang versioning=semver
    - "1.25.11-trixie"
    - "1.25-trixie"
    # renovate: datasource=golang-version depName=golang versioning=semver
    - "1.25.11"
    - "1.25"
  debian_variant: "trixie"
  build_args:
    # renovate: datasource=golang-version depName=golang
    GOLANG_VERSION: "1.25.11"
    # renovate: datasource=go depName=golang.org/x/tools/gopls
    GOPLS_VERSION: "v0.22.0"

- variant: "1.25-bookworm"
  tags:
    # renovate: datasource=golang-version depName=golang versioning=semver
    - "1.25.11-bookworm"
    - "1.25-bookworm"
  debian_variant: "bookworm"
  build_args:
    # renovate: datasource=golang-version depName=golang
    GOLANG_VERSION: "1.25.11"
    # renovate: datasource=go depName=golang.org/x/tools/gopls
    GOPLS_VERSION: "v0.22.0"
