- variant: "1.26-trixie"
  tags:
    # renovate: datasource=docker depName=golang versioning=semver
    - "1.26.4-trixie"
    - "1.26-trixie"
    - "1-trixie"
    # renovate: datasource=docker depName=golang versioning=semver
    - "1.26.4"
    - "1.26"
    - "1"
  debian_variant: "trixie"
  build_args:
    # renovate: datasource=docker depName=golang
    GOLANG_TAG: "1.26.4-trixie@sha256:76a29248dedcd75870e95cbd90cc8cb356db082404ac7d3a5803f276c3ba79c9"

- variant: "1.26-bookworm"
  tags:
    # renovate: datasource=docker depName=golang versioning=semver
    - "1.26.4-bookworm"
    - "1.26-bookworm"
    - "1-bookworm"
  debian_variant: "bookworm"
  build_args:
    # renovate: datasource=docker depName=golang
    GOLANG_TAG: "1.26.4-bookworm@sha256:b305420a68d0f229d91eb3b3ed9e519fcf2cf5461da4bef997bf927e8c0bfd2b"

- variant: "1.25-trixie"
  tags:
    # renovate: datasource=docker depName=golang versioning=semver
    - "1.25.11-trixie"
    - "1.25-trixie"
    # renovate: datasource=docker depName=golang versioning=semver
    - "1.25.11"
    - "1.25"
  debian_variant: "trixie"
  build_args:
    # renovate: datasource=docker depName=golang
    GOLANG_TAG: "1.25.11-trixie@sha256:08d16bd2719d18db2f97cae2192ee3f911f57546dd3b2db373c328015f256109"

- variant: "1.25-bookworm"
  tags:
    # renovate: datasource=docker depName=golang versioning=semver
    - "1.25.11-bookworm"
    - "1.25-bookworm"
  debian_variant: "bookworm"
  build_args:
    # renovate: datasource=docker depName=golang
    GOLANG_TAG: "1.25.11-bookworm@sha256:b96f24a8d7d010ea0acb9c3ba99064740f02b6b984612b28bd3c9c5ab9453e38"
