- variant: "trixie"
  tags:
    - "trixie"
  build_args:
    # renovate: datasource=docker depName=debian versioning=debian
    DEBIAN_TAG: "trixie-20260610@sha256:fe7312b5f05bf5f43fad76bcd8945642e4e47a68aefd1b73f447615899d0fac1"

- variant: "bookworm"
  tags:
    - "bookworm"
  build_args:
    # renovate: datasource=docker depName=debian versioning=debian
    DEBIAN_TAG: "bookworm-20260610@sha256:49ba348354a28e39c70beffd6cf43bdb8d55d81ce4b746b0428717d054b8bbc4"
