description: "Minimal Debian base image for Dev Containers: verified upstreams, SLSA provenance"
variants:
  - variant: "trixie"
    tags:
      - "trixie"
    build_args:
      # renovate: datasource=docker depName=debian versioning=debian
      DEBIAN_TAG: "trixie-20260918@sha256:a792639161fbe8a4249347e72ea43d0fa6039c97413097e3aa225406173ec1ec"

  - variant: "bookworm"
    tags:
      - "bookworm"
    build_args:
      # renovate: datasource=docker depName=debian versioning=debian
      DEBIAN_TAG: "bookworm-20260918@sha256:f37a335e82bca302e955fa39f9dfe28f1be618f016f8a2b56318e5a5111afc26"
