name: Lint

on:
  pull_request:
    paths:
      - .github/workflows/lint.yml
      - '**/Dockerfile'
      - '**/*.sh'
      - '**/devcontainer.json'
      - .hadolint.yaml
  push:
    branches:
      - main

permissions: {}

jobs:
  hadolint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          recursive: true
          config: .hadolint.yaml

  shellcheck:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Lint shell scripts
        run: find . -type f -name "*.sh" -exec shellcheck {} +

  decolint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      # renovate: datasource=docker registryUrl=https://ghcr.io depName=bare-devcontainer/decolint versioning=docker
      DECOLINT_TAG: "latest@sha256:2a5a5427ab8b544b2c1ca8a7636558f1a5384ee00e2c17b983fa32f4863c0d43"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Lint devcontainer configurations
        run: |
          docker run --rm -v "$PWD:/workspace" ghcr.io/bare-devcontainer/decolint:${{ env.DECOLINT_TAG }} --format=github .
