name: Lint

on:
  pull_request:
    paths:
      - .github/workflows/lint.yml
      - '**/Dockerfile'
      - '**/*.sh'
      - '**/devcontainer.json'
      - .hadolint.yaml
  push:
    branches:
      - main

permissions: {}

jobs:
  hadolint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          recursive: true
          config: .hadolint.yaml

  shellcheck:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Lint shell scripts
        run: find . -type f -name "*.sh" -exec shellcheck {} +

  decolint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      # renovate: datasource=docker registryUrl=https://ghcr.io depName=bare-devcontainer/decolint versioning=docker
      DECOLINT_TAG: "latest@sha256:316b1ac0191451832ad896241b6e2a1162e8b14a95c6bcee576e58376d5f4334"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Lint devcontainer configurations
        run: |
          docker run --rm -v "$PWD:/workspace" ghcr.io/bare-devcontainer/decolint:${{ env.DECOLINT_TAG }} --format=github .
